SET ECHO 		OFF
SET FEEDBACK		OFF
SET LINESIZE		100
SET PAGESIZE 		300
COLUMN	OBJECT_NAME     FORMAT A20 HEADING "Object name"
COLUMN	OWNER           FORMAT A20 HEADING "Owner"
COLUMN 	STATISTIC_NAME  FORMAT A25 HEADING "Statistic name"
COLUMN 	STAT_NAME       FORMAT A40 HEADING "Statistic name"
COLUMN  INCR 		FORMAT 9,999,999,999 HEADING "Statistic value"
COLUMN 	STATISTIC_VALUE	FORMAT 9,999,999,999 HEADING "Statistic value"

connect system/oracle

CREATE TABLE OPSTAT_TABLE(
OWNER		VARCHAR(30)	NOT NULL,
OBJECT_NAME	VARCHAR(30)	NOT NULL,
STATISTIC_NAME	VARCHAR(64)	NOT NULL,
VALUE		NUMBER		NOT NULL,
TS		TIMESTAMP	NOT NULL,
  CONSTRAINT OPSTAT_TABLE_PKEY PRIMARY KEY(TS,OWNER,OBJECT_NAME,STATISTIC_NAME) );

CREATE TABLE SYSSTAT_TABLE(
NAME            VARCHAR(64)     NOT NULL,
VALUE           NUMBER          NOT NULL,
  CONSTRAINT SYSSTAT_TABLE_PKEY PRIMARY KEY(NAME) ); 

ACCEPT SCRIPT		CHAR PROMPT 'Script name>'
SET TERMOUT		OFF

INSERT INTO OPSTAT_TABLE (
	SELECT	OWNER,
 		OBJECT_NAME,
 		STATISTIC_NAME,
 		VALUE,
		SYSTIMESTAMP
	FROM  	V$SEGMENT_STATISTICS
	WHERE 	OWNER = 'TPCHR' AND
		STATISTIC_NAME IN ('logical reads',
				   'physical reads',
				   'physical writes' ) );

INSERT INTO SYSSTAT_TABLE (
	SELECT	NAME,
 		VALUE
	FROM  	V$SYSSTAT
	WHERE 	NAME LIKE 'bytes sent via SQL*Net to client' OR
                NAME LIKE 'bytes received via SQL*Net from client');


COMMIT;

CONNECT tpchr/oracle
@&SCRIPT

SET TERMOUT		ON

CONNECT system/oracle
SELECT	V$SEGMENT_STATISTICS.OWNER,
 	V$SEGMENT_STATISTICS.OBJECT_NAME,
 	V$SEGMENT_STATISTICS.STATISTIC_NAME,
 	V$SEGMENT_STATISTICS.VALUE - NVL(OPSTAT_TABLE.VALUE,0) INCR
FROM  	V$SEGMENT_STATISTICS LEFT OUTER JOIN OPSTAT_TABLE
	                    ON V$SEGMENT_STATISTICS.OWNER = OPSTAT_TABLE.OWNER AND
	                       V$SEGMENT_STATISTICS.OBJECT_NAME = OPSTAT_TABLE.OBJECT_NAME AND
	                       V$SEGMENT_STATISTICS.STATISTIC_NAME = OPSTAT_TABLE.STATISTIC_NAME
WHERE 	V$SEGMENT_STATISTICS.OWNER = 'TPCHR' AND
 	( V$SEGMENT_STATISTICS.VALUE - NVL(OPSTAT_TABLE.VALUE,0) ) <> 0 AND
	V$SEGMENT_STATISTICS.OBJECT_NAME <> 'PLAN_TABLE' AND 
	V$SEGMENT_STATISTICS.STATISTIC_NAME IN ('logical reads',
			 			'physical reads',
			   			'physical writes' )
ORDER BY V$SEGMENT_STATISTICS.OBJECT_NAME, V$SEGMENT_STATISTICS.STATISTIC_NAME;

SELECT V$SYSSTAT.NAME STAT_NAME,
       V$SYSSTAT.VALUE - SYSSTAT_TABLE.VALUE STATISTIC_VALUE
FROM SYSSTAT_TABLE JOIN V$SYSSTAT
                   ON SYSSTAT_TABLE.NAME = V$SYSSTAT.NAME
WHERE SYSSTAT_TABLE.NAME LIKE 'bytes sent via SQL*Net to client' OR
      SYSSTAT_TABLE.NAME LIKE 'bytes received via SQL*Net from client';

DROP TABLE OPSTAT_TABLE PURGE;
DROP TABLE SYSSTAT_TABLE PURGE;

SET FEEDBACK 		ON
SET ECHO 		ON;

prompt Done.
