SELECT count(*)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE NATION.N_NAME = 'PERU';

SELECT count(S_NAME || N_NAME || P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 7;

SELECT COUNT(S_NAME || N_NAME || P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 4;

SELECT COUNT(*)
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
            JOIN NATION    ON C_NATIONKEY = N_NATIONKEY
	    JOIN REGION    ON N_REGIONKEY = R_REGIONKEY
WHERE REGION.R_NAME = 'AFRICA';

SELECT COUNT(*)
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
            JOIN NATION    ON C_NATIONKEY = N_NATIONKEY
	    JOIN REGION    ON N_REGIONKEY = R_REGIONKEY
WHERE REGION.R_NAME = 'ASIA'; 

SELECT count(S_NAME|| N_NAME|| P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 1;

SELECT COUNT(*)
FROM ORDERS
WHERE O_TOTALPRICE > 100;

SELECT COUNT(S_NAME || N_NAME || P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 2

SELECT count(*) NONE
FROM LINEITEM
WHERE L_SHIPINSTRUCT LIKE '%NONE%';

SELECT COUNT(C_CUSTKEY || R_NAME)
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
            JOIN NATION    ON C_NATIONKEY = N_NATIONKEY
	    JOIN REGION    ON N_REGIONKEY = R_REGIONKEY
WHERE REGION.R_NAME = 'EUROPE'; 

SELECT count(S_NAME || N_NAME || P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 3;

SELECT count(R_NAME)
FROM REGION;

SELECT COUNT(*)
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
            JOIN NATION    ON C_NATIONKEY = N_NATIONKEY
	    JOIN REGION    ON N_REGIONKEY = R_REGIONKEY
WHERE REGION.R_NAME = 'AMERICA'; 

SELECT count(*)
FROM SUPPLIER
WHERE S_ACCTBAL > 0;

SELECT N_NAME
FROM NATION;

SELECT COUNT(*)
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
            JOIN NATION    ON C_NATIONKEY = N_NATIONKEY
	    JOIN REGION    ON N_REGIONKEY = R_REGIONKEY
WHERE REGION.R_NAME = 'AMERICA';

SELECT COUNT(*)
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
            JOIN NATION    ON C_NATIONKEY = N_NATIONKEY
	    JOIN REGION    ON N_REGIONKEY = R_REGIONKEY
WHERE REGION.R_NAME = 'AFRICA';

SELECT COUNT(*)
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
            JOIN NATION    ON C_NATIONKEY = N_NATIONKEY
	    JOIN REGION    ON N_REGIONKEY = R_REGIONKEY
WHERE REGION.R_NAME = 'ASIA';

SELECT count(*) TAKE
FROM LINEITEM
WHERE L_SHIPINSTRUCT LIKE '%TAKE BACK RETURN%';
SET ECHO ON

SELECT count(S_NAME || N_NAME || P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 5

SELECT count(S_NAME || N_NAME || P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 6;

SELECT count(S_NAME || N_NAME || P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 7;

SELECT COUNT(S_NAME || N_NAME || P_NAME)
FROM PARTSUPP JOIN SUPPLIER ON PS_SUPPKEY = S_SUPPKEY 
              JOIN PART     ON PS_PARTKEY = P_PARTKEY
              JOIN NATION   ON S_NATIONKEY = N_NATIONKEY
WHERE S_SUPPKEY = 4;

SELECT COUNT(*)
FROM ORDERS JOIN CUSTOMER ON O_CUSTKEY = C_CUSTKEY
            JOIN NATION    ON C_NATIONKEY = N_NATIONKEY
	    JOIN REGION    ON N_REGIONKEY = R_REGIONKEY
WHERE REGION.R_NAME = 'AFRICA'; 


