CREATE TABLE PART_NBT(
P_PARTKEY 	NUMBER(12) 	NOT NULL,
P_NAME		VARCHAR(55)	NOT NULL,
P_BRAND		CHAR(10)	NOT NULL,
P_TYPE		VARCHAR(25)	NOT NULL,
	CONSTRAINT PART_NBT_PKEY PRIMARY KEY (P_PARTKEY),
        CONSTRAINT PART_NBT_FKEY FOREIGN KEY (P_PARTKEY)
                   REFERENCES PART(P_PARTKEY),
	CONSTRAINT PART_NBT_CHECK CHECK(P_PARTKEY >= 0) );

CREATE TABLE PART_COMMENTS(
P_PARTKEY 	NUMBER(12) 	NOT NULL,
P_COMMENT	VARCHAR(23)	NOT NULL,
	CONSTRAINT PART_COMMENTS_PKEY PRIMARY KEY (P_PARTKEY),
        CONSTRAINT PART_COMMENTS_FKEY FOREIGN KEY (P_PARTKEY)
                   REFERENCES PART(P_PARTKEY) );

CREATE TABLE PART_OTHERS(
P_PARTKEY 	NUMBER(12) 	NOT NULL,
P_MFGR		VARCHAR(25)	NOT NULL,
P_SIZE		NUMBER(12)	NOT NULL,
P_CONTAINER 	CHAR(10)	NOT NULL,
P_RETAILPRICE	NUMBER(12,2)	NOT NULL,
	CONSTRAINT PART_OTHERS_PKEY PRIMARY KEY (P_PARTKEY),
        CONSTRAINT PART_OTHERS_FKEY FOREIGN KEY (P_PARTKEY)
                   REFERENCES PART(P_PARTKEY),
	CONSTRAINT PART_OTHERS_CHECK1 CHECK(P_PARTKEY >= 0),
	CONSTRAINT PART_OTHERS_CHECK2 CHECK(P_SIZE >= 0),
	CONSTRAINT PART_OTHERS_CHECK3 CHECK(P_RETAILPRICE >= 0) );

DECLARE

BEGIN

  FOR PARTKEY IN (SELECT DISTINCT PS_PARTKEY FROM PARTSUPP)
  LOOP
    INSERT INTO PART_NBT ( SELECT P_PARTKEY, P_NAME, P_BRAND, P_TYPE
                       FROM PART
                       WHERE P_PARTKEY = PARTKEY.PS_PARTKEY );
    COMMIT;
  END LOOP;

  FOR PARTKEY IN (SELECT DISTINCT PS_PARTKEY FROM PARTSUPP)
  LOOP
    INSERT INTO PART_COMMENTS ( SELECT P_PARTKEY, P_COMMENT
                                FROM PART
                                WHERE P_PARTKEY = PARTKEY.PS_PARTKEY );
    COMMIT;


  END LOOP;

  FOR PARTKEY IN (SELECT DISTINCT PS_PARTKEY FROM PARTSUPP)
  LOOP
    INSERT INTO PART_OTHERS ( SELECT P_PARTKEY, P_MFGR, P_SIZE, P_CONTAINER, 
                                     P_RETAILPRICE 
                              FROM PART
                              WHERE P_PARTKEY = PARTKEY.PS_PARTKEY );
    COMMIT;
  END LOOP;
  
END;
/

DROP TABLE PART_NBT PURGE;
DROP TABLE PART_COMMENTS PURGE;
DROP TABLE PART_OTHERS PURGE;
