SELECT L_PARTKEY, L_SUPPKEY, SUM(L_QUANTITY)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY;

SELECT L_SUPPKEY, L_ORDERKEY, SUM(L_DISCOUNT)
FROM LINEITEM
GROUP BY L_SUPPKEY, L_ORDERKEY;

SELECT L_SUPPKEY, L_ORDERKEY, SUM(L_QUANTITY)
FROM LINEITEM
GROUP BY L_SUPPKEY, L_ORDERKEY;

SELECT L_PARTKEY, L_SUPPKEY, COUNT(L_DISCOUNT)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY;

SELECT L_PARTKEY, L_SUPPKEY, SUM(L_DISCOUNT)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY;

SELECT L_SUPPKEY, COUNT(DISTINCT L_DISCOUNT)
FROM LINEITEM
GROUP BY L_SUPPKEY;

SELECT L_PARTKEY, L_SUPPKEY, COUNT(DISTINCT L_DISCOUNT)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY;

